# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: tflint-ruleset-stegra
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm
      - linux_arm64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
    files:
      - none*
checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: ./dist/raw/*
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
release:
  github:
    owner: stegraab
    name: tflint-ruleset-stegra
  name_template: "{{ .Tag }}"
  draft: false
  prerelease: auto
